### PR TITLE
Prototype of local visualizations like .NET

### PR DESCRIPTION
**Pull request by cartermp**
You can verify this like so (substitute your preferred key and service name):

```shell
export OTEL_SERVICE_NAME="phillips-happy-fun-time"
export HONEYCOMB_API_KEY=lol
export HONEYCOMB_ENABLE_LOCAL_VISUALIZATIONS=true
go run ./example/example.go 
```

And you'll see something like this:

```
Trace for foo
Honeycomb link: http://ui.honeycomb.io/demo/environments/test/datasets/phillips-happy-fun-time/trace?trace_id=b29917a4219627c130e1c21cf1ef5ea1
```

Which will take you to that trace, just like in the .NET distro!

Some things that should probably be done:

- [x] This should probably be an exporter, not a processor, since stuff could still be in the buffer when the link is made
- [x] Support classic
- [ ] ~~Support whatever the configured endpoint is~~ (nope, not a thing yet)
- [x] Tests
- [x] ~~Figure out a better way to make it programmatically accessible maybe?~~

What's y'all's thoughts?

### CODE REVIEW

**Comment by cartermp** [comment]
I think our testing is kinda borky. I get this locally:

```
--- FAIL: TestServiceNameDefaultsToUnknownServiceWhenNotSet (0.06s)
    honeycomb_test.go:195: 
                Error Trace:    /workspace/honeycomb-opentelemetry-go/honeycomb_test.go:195
                Error:          Not equal: 
                                expected: "unknown_service:go"
                                actual  : ""
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -unknown_service:go
                                +
                Test:           TestServiceNameDefaultsToUnknownServiceWhenNotSet
```

But that's the only failure.

On CI, that passes! But a different test fails.

**Comment by cartermp** [comment]
Okay, running tests locally in a fresh dev env now matches CI. Progress?

**Comment by cartermp** [comment]
I haven't added a test for the exporter itself. That would require stubbing the endpoint call I believe.

That _could_ be done, but I'd need to go learn how to do that in Go, heh.

At any rate, this is ready for review.

**Comment by MikeGoldsmith** [comment]
Created PR to make some amendments: https://github.com/cartermp/honeycomb-opentelemetry-go/pull/1
(Had to do as PR because you used a fork 😛)

My only real main concern is the `WithLocalVisualizations` option because you have to provide your apikey and service name again. Ideally we should be able to detect those as part of the `getVendorOptionSetters` func but isn't straight forward. Do you think we could do without the programmatic option for now?

**Comment by cartermp** [comment]
> Do you think we could do without the programmatic option for now?

Yep!

**Review by MikeGoldsmith — APPROVED** [review]

**Pull request merged**
